### ISSUE TITLE
ウェブサイトにアクセスできない不具合

### ISSUE THREAD

**Issue by kawabatakaito** [mountain-gorilla-inc/beginner-lesson1#6]
`make init` 実行後、`http://127.0.0.1:8080`にアクセスすると下図のエラーが出る

Target class [Laravel\Passport\Http\Middleware\CreateFreshApiToken] does not exist.
![image](https://github.com/mountain-gorilla-inc/beginner-lesson1/assets/74036050/3a421cb8-bd99-4652-87ec-26986b161011)

**Comment by kawabatakaito** [comment]
```
App\Http\Middleware\ ForceHttpProtocol: 22handle

<?php



namespace App\Http\Middleware;



use Closure;



class ForceHttpProtocol

{

    /**

     * Handle an incoming request.

     *

     * @param  \Illuminate\Http\Request  $request

     * @param  \Closure  $next

     * @return mixed

     */

    public function handle($request, Closure $next)

    {

        if (!$request->secure() && env('APP_ENV') === 'production') { // 本番環境のみ常時SSL化する

            return redirect()->secure($request->getRequestUri());

        }



        return $next($request);

    }

}


```

**Comment by mg-shinozuka** [comment]
```infra/docker/php/Dockerfile```に記述してある
```composer require laravel/passport && \```がインストール出来ていない事が判明いたしました。
上記をインストールすると正常に画面に飛ぶことが出来ます！

![image](https://github.com/mountain-gorilla-inc/beginner-lesson1/assets/129820712/f5836f3d-31e6-4a60-af8a-d44f64a0c5d1)
